repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: launchpad-ppas
shallow_clone: false
directory: kolla
release: master-wave-6
depends_on: ''
source_sha: cd36091e3b20a33df27cae4130085b75c3f9dcab
previous_source_sha: 0cbc63835b7d24c726da1bb44a46fbdd3e09680e
skip_rebase: true
skip_claude: true
