repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: master-patches
shallow_clone: true
directory: kolla
release: master
depends_on: ''
source_sha: 8e912a9db7f013a1abfc1e70a829e435d50622db
previous_source_sha: 4b869009c3336ab0f68353e71fcef30dd4cf44b3
