repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: master-patches
shallow_clone: true
directory: kolla
release: master
depends_on: ''
source_sha: f38dbfcc5e7e7edd1e754939272a6a561085e1ef
previous_source_sha: 5b643d55c3eba44a9b82ed792bfd9d1c593bbf67
