repo: https://opendev.org/openstack/kolla
source_branch: stable/2025.2
destination_branch: stable/2025.2-patches
shallow_clone: true
directory: kolla
release: 2025.2
depends_on: ''
source_sha: 11afc796b3a4a4ca2e83072c829fdd4ea9aaa505
previous_source_sha: 0d0b8dda3a8b50c0f6d5dace2246132f88c2dfd3
skip_rebase: true
