repo: https://opendev.org/openstack/kolla
source_branch: stable/2025.2
destination_branch: stable/2025.2-patches
shallow_clone: true
directory: kolla
release: 2025.2
depends_on: ''
source_sha: f77dbd13d16bf507a9a7240d7e10047f381b2739
previous_source_sha: 91e37843fefaf46f6358093c28c966c46e6f8d2f
skip_rebase: true
