repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: bug-2162860
shallow_clone: false
directory: kolla-ansible
release: master-bug-2162860
depends_on: ''
source_sha: 1a681814eb19a4840ca307a25f21b2907b432272
previous_source_sha: 7b5486310803fc25c9ff3f3b625096efbbd43341
skip_rebase: true
skip_claude: true
