repo: https://github.com/openstack/openstacksdk
source_branch: stable/2025.2
destination_branch: stable/2025.1-patches
shallow_clone: false
directory: openstacksdk
release: 2025.1
depends_on: ''
source_sha: 8cadd9d3267e1950d1e0089dd1c4dc15b652b598
