repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2026.1
destination_branch: libvirtd-tuning
shallow_clone: false
directory: kolla-ansible
release: 2026.1-libvirtd-tuning
depends_on: ''
source_sha: 75a9dcd132b0a5aab69bf234dd621c9035208174
skip_rebase: true
skip_claude: true
previous_source_sha: 630366841302ea9e62e15b693b8b678e0fcfa25e
