repo: https://opendev.org/openstack/ansible-collection-kolla
source_branch: master
destination_branch: master-patches
shallow_clone: false
directory: ansible-collection-kolla
release: master
depends_on: ''
source_sha: 8c016fb86cad07e379a4eea8964d553171ebcb23
previous_source_sha: 11fa4c282fdde0dc60365c7890712325a226472d
