repo: https://opendev.org/openstack/requirements
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: true
directory: requirements
release: 2025.1
depends_on: ''
source_sha: c65c03328454f762ef0e173f77b1ed05e1d80937
previous_source_sha: c10699eb2e1de27287feeb35ea29db2cf58bf4f8
skip_rebase: true
