repo: https://opendev.org/openstack/requirements
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: true
directory: requirements
release: 2025.1
depends_on: ''
source_sha: 7b62011174e030d696d7ca42eb11ad82f2b19a3d
previous_source_sha: 65790a52f92c0bdba49f0e137f2e1038ace27cb8
skip_rebase: true
