repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: master-patches
shallow_clone: false
directory: kolla-ansible
release: master
depends_on: requirements
source_sha: baca5f2665f437575afa7325524c6e6eb0c66586
previous_source_sha: 81bb9bdda13067c1e20054407e9385da4b1dc2d3
