repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: master-patches
shallow_clone: false
directory: kolla-ansible
release: master
depends_on: ''
source_sha: 120aa1eef97cdfe8da6a769fcbcd0c37414d66c9
previous_source_sha: fb256c12049093b5b37d607e57c26cd4a36d5e9e
