repo: https://github.com/openstack/python-openstackclient
source_branch: stable/2025.2
destination_branch: libvirt-spice-direct
shallow_clone: false
directory: python-openstackclient
release: 2025.1
depends_on: openstacksdk-2025.1
source_sha: ad2689d1d346e12787d8ce7714427237b65afc2f
previous_source_sha: 78ef2f592268d0f18419da231d376970d70f86ef
