repo: https://opendev.org/openstack/python-openstackclient
source_branch: stable/2025.2
destination_branch: libvirt-spice-direct
shallow_clone: false
directory: python-openstackclient
release: 2025.1
depends_on: openstacksdk-2025.1
source_sha: cc866e71076cefbe86bddad479d4f3229ef9171a
previous_source_sha: ad2689d1d346e12787d8ce7714427237b65afc2f
