repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: kerbside-overridable-proxy-wheel
shallow_clone: false
directory: kolla
release: master-wave-8
depends_on: ''
source_sha: 4b869009c3336ab0f68353e71fcef30dd4cf44b3
previous_source_sha: 5d77668da8167435e4ac860392994f19ec733a46
skip_rebase: true
skip_claude: true
