repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: kerbside-overridable-proxy-wheel
shallow_clone: false
directory: kolla
release: master-wave-8
depends_on: ''
source_sha: a2515e086b43d859be67c8b1f4af82d4a75a5a1c
previous_source_sha: 455303aef30d245485b34ac22cabd5ab3cab562c
skip_rebase: true
skip_claude: true
