repo: https://github.com/openstack/kolla-ansible
source_branch: master
destination_branch: dry-up-logrotate
shallow_clone: false
directory: kolla-ansible
release: master-wave-1.1
depends_on: ''
source_sha: 0079f20030ec52d43a8ea4503cd4fad60dcb35fb43559c3db7965f0a46199629aef261fd1106c89a
previous_source_sha: 7236849ee40d136b3c796080167f259e7b110597
skip_rebase: true
skip_claude: true
