repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: dry-up-logrotate
shallow_clone: false
directory: kolla-ansible
release: master-wave-1.1
depends_on: ''
source_sha: d17f64dd5ef0a5e1dafb2fd31b4bef46bf7d324d
previous_source_sha: 77e9d23a20fa39fe49f03210b6a20bc463c31078
skip_rebase: true
skip_claude: true
