repo: https://github.com/openstack/kolla-ansible
source_branch: master
destination_branch: dry-up-logrotate
shallow_clone: false
directory: kolla-ansible
release: master-wave-1.1
depends_on: ''
source_sha: f699a56a8ac9706c6c33edf00e5056f8ce1dc896
previous_source_sha: 496dd763d82eaa666549556c28f1f4fb74a8d446
skip_rebase: true
skip_claude: true
