repo: https://opendev.org/openstack/kolla
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: true
directory: kolla
release: 2025.1
depends_on: ''
source_sha: 23e5988e4bc1f8deb626b12d8c5d50060da94387
previous_source_sha: 69b487c67ff7e18293d9a326a2df15b5acaa7301
skip_rebase: true
