repo: https://github.com/openstack/kolla
source_branch: master
destination_branch: debian-trixie
shallow_clone: true
directory: kolla
release: debian-trixie
depends_on: ''
source_sha: 35f7b3c3426662877d4f8fc2e3c517697ffba6d9
previous_source_sha: 96b54022857ccef8dc6bb11789abe32119827109
