repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2025.2-periodic-stable-tox
depends_on: ''
source_sha: 257605a5e70491a884823ce8f03c497e51bf36c1
previous_source_sha: bf682cde26e211d317b22540f4b0deb1c4f77633
skip_rebase: true
skip_claude: true
