repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2025.2-periodic-stable-tox
depends_on: ''
source_sha: 50d85c58c5bf034dbb7946826094c1ea1ad10191
previous_source_sha: 6112487ba772f31a16051016f1247a0ab754aefe
skip_rebase: true
skip_claude: true
