repo: https://github.com/openstack/kolla-ansible
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: false
directory: kolla-ansible
release: 2025.1
depends_on: ''
source_sha: dbdd7f663341b9c46987761261fcaf9c6e8a2989
previous_source_sha: d63160ab69fcd8412870982c9901ca53b6c0db57
