repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: false
directory: kolla-ansible
release: 2025.1
depends_on: ''
source_sha: 16257a5187d5b081337b8e17f6c3a068109a8f9f
previous_source_sha: a9bc2d83e977974edca8480003407a937aa2d1c6
