repo: https://opendev.org/openstack/kolla
source_branch: stable/2025.1
destination_branch: bug/2138186
shallow_clone: false
directory: kolla
release: 2025.1
depends_on: ''
skip_rebase: true
skip_claude: true
source_sha: d810e07df898e3f49409524f7e6498bf0793f7d2
previous_source_sha: 69b487c67ff7e18293d9a326a2df15b5acaa7301
