repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: magnum-setuptools-pin
shallow_clone: false
directory: kolla
release: master-kolla-magnum-setuptools-pin
depends_on: ''
source_sha: cd36091e3b20a33df27cae4130085b75c3f9dcab
previous_source_sha: cd36091e3b20a33df27cae4130085b75c3f9dcab
skip_rebase: true
skip_claude: true
repush: true
