repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: spice-direct-consoles
shallow_clone: false
directory: kolla-ansible
release: master-wave-1
depends_on: ''
source_sha: 68225c2396cbd018f3671686eae03b8a450be50e
previous_source_sha: b79f76f4849bafd50d65b10f0e9015873cd7a76a
skip_rebase: true
skip_claude: true
