repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: spice-direct-consoles
shallow_clone: false
directory: kolla-ansible
release: master-wave-1
depends_on: ''
source_sha: 2c244498c1419b076af83acd6903bad63dd53f7b
previous_source_sha: 81bb9bdda13067c1e20054407e9385da4b1dc2d3
skip_rebase: true
skip_claude: true
