repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: mariadb-collations
shallow_clone: false
directory: kolla-ansible
release: master-kolla-ansible-mariadb-collations
depends_on: ''
source_sha: c8c7a0f6d01ec28cbc4454ef05e22b5a7cd78cf3
previous_source_sha: 2f64452fbad843816d74b7584ea81d33d8054a14
skip_rebase: true
skip_claude: true
repush: true
