repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: mariadb-collations
shallow_clone: false
directory: kolla-ansible
release: master-kolla-ansible-mariadb-collations
depends_on: ''
source_sha: 1358348cf5e8b0af5971e0873c32d2430a6967b8
previous_source_sha: 686d3f678754d722ef8b0cdc766152b3e55781be
skip_rebase: true
skip_claude: true
