repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: json-logging
shallow_clone: false
directory: kolla-ansible
release: master-json-logging
depends_on: ''
source_sha: e73332af58eeb1e019c99ad8c42812dc18f8ae00
previous_source_sha: 54aab1476fb5be5519294331be75c91924842a1e
skip_rebase: true
skip_claude: true
repush: true
