repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: launchpad-ppas
shallow_clone: false
directory: kolla
release: master-wave-6
depends_on: ''
source_sha: cbdbd894b06b049e36ecd4fab4d0ecc3a49e0c00
previous_source_sha: f38dbfcc5e7e7edd1e754939272a6a561085e1ef
skip_rebase: true
skip_claude: true
