repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: launchpad-ppas
shallow_clone: false
directory: kolla
release: master-wave-6
depends_on: ''
source_sha: e2979830cd614618f7c51031bdd6bffc80ea694e
previous_source_sha: 5aabec47f057d9cb32aab520d666e51bd9ee37c6
skip_rebase: true
skip_claude: true
