repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: fluentd-tail-patience
shallow_clone: false
directory: kolla-ansible
release: master-fluentd-tail-patience
depends_on: ''
source_sha: 686d3f678754d722ef8b0cdc766152b3e55781be
previous_source_sha: f61750c7ea822d9996a391d4b5e8795350368b66
skip_rebase: true
skip_claude: true
