repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: fluentd-tail-patience
shallow_clone: false
directory: kolla-ansible
release: master-fluentd-tail-patience
depends_on: ''
source_sha: 6c8d3b7d363e62b9a5da47bdbedc4adad016cfb9
previous_source_sha: 39454a4a0d4ebcdf1ee510216d3038044ddef1bc
skip_rebase: true
skip_claude: true
