repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: fluentd-tail-patience
shallow_clone: false
directory: kolla-ansible
release: master-fluentd-tail-patience
depends_on: ''
source_sha: e7c2b4010a99d7c1fdb4fb885abc5391a328e033
previous_source_sha: 6f2df724ab38da9c99ae9136b271cf15b1d13055
skip_rebase: false
skip_claude: true
repush: true
