repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: influxdb-repo-gpg-key
shallow_clone: false
directory: kolla
release: master-wave-2
depends_on: ''
source_sha: f179e83e55320464dc66922fcb0aca88463696cc
previous_source_sha: a590ac5a5e94355081bd7192e776b6b5ac2851c2
skip_rebase: true
skip_claude: true
