repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.1
destination_branch: virtlogd-preflight
shallow_clone: false
directory: kolla-ansible
release: 2025.1-virtlogd
depends_on: ''
source_sha: f740c5beb25f9eedee8fa1916faace8188892664
skip_rebase: true
skip_claude: true
previous_source_sha: 4b907001132ec7d59f73affb54137598ca4ba35f
