repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: stable/2025.2-patches
shallow_clone: true
directory: kolla-ansible
release: 2025.2
depends_on: ''
source_sha: 420f70d7944c310d989daeed34cd71d4d6bfd165
previous_source_sha: 6a2deb0cbe10338bb35a077bc327828386f689c4
