repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: stable/2025.2-patches
shallow_clone: true
directory: kolla-ansible
release: 2025.2
depends_on: ''
source_sha: 304115816a5c81ff7a6a1eb03113deb8441248c0
previous_source_sha: 374d3c805f7effcad49e25f7b5e1730faf5bee05
skip_rebase: true
