repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: stable/2025.2-patches
shallow_clone: true
directory: kolla-ansible
release: 2025.2
depends_on: ''
source_sha: e3f7979b9cbeb6b016dd6c057ce4bca6beaabe36
previous_source_sha: b5bc3bf2579ca29c649a8a254dd733ae12c5f106
skip_rebase: true
