repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: spice-direct-consoles
shallow_clone: false
directory: kolla
release: master-wave-5
depends_on: ''
source_sha: 205bc944be6c67d81bc2b9f3b7d3303faaf5b866
previous_source_sha: f1d20c6fd31b8aeb7f14a293f8c69c275b2d22cf
skip_rebase: true
skip_claude: true
