repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2026.1
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2026.1-periodic-stable-tox
depends_on: ''
source_sha: 183fa41b039fee6fc824547e85ee3abc61a1aa84
previous_source_sha: b8d02a18fdcf69194cdbb89798ae6081b6ef2366
skip_rebase: true
skip_claude: true
