repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2026.1
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2026.1-periodic-stable-tox
depends_on: ''
source_sha: cafb8d5e1af143c83ca3dfe239e50d8bbc5f6ac5
previous_source_sha: 469fbe0b15c06fcf464b6c5f5550c275f4537625
skip_rebase: true
skip_claude: true
