repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: mariadb-retries
shallow_clone: false
directory: kolla-ansible
release: master-wave-6
depends_on: ''
source_sha: 3e2efef4ce12241bb44582f660a5ad8f249b50b3
previous_source_sha: f33e8411b623a7a32aa78a24740a42eea81c0bef
skip_rebase: true
skip_claude: true
