repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: mariadb-retries
shallow_clone: false
directory: kolla-ansible
release: master-wave-6
depends_on: ''
source_sha: 188f616f93e21c978a9d6db39c680eacf643094b
previous_source_sha: 1009d4da8e96d6342f4b1e743994bb61cda8d373
skip_rebase: true
skip_claude: true
