repo: https://opendev.org/openstack/magnum
source_branch: master
destination_branch: mariadb-collations
shallow_clone: false
directory: magnum
release: master-magnum-mariadb-collations
depends_on: ''
source_sha: 547639b13e8d60eb7c1f5bd332d7030897150686
previous_source_sha: 683f34169d79503b93c94d2e23da6aec9e7bba14
skip_rebase: true
skip_claude: true
repush: true
