repo: https://opendev.org/openstack/magnum
source_branch: master
destination_branch: mariadb-collations
shallow_clone: false
directory: magnum
release: master-magnum-mariadb-collations
depends_on: ''
source_sha: f902fbb59f79f5ea8e4ef4e2b7547226bc2e2451
previous_source_sha: 547639b13e8d60eb7c1f5bd332d7030897150686
skip_rebase: true
skip_claude: true
repush: true
