repo: https://github.com/openstack/nova
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: true
directory: nova
release: 2025.1
depends_on: ''
source_sha: 3b97b00f0e2b1d7d10b71696e82fabb5582ce92a
previous_source_sha: 3b97b00f0e2b1d7d10b71696e82fabb5582ce92a
