repo: https://github.com/openstack/nova
source_branch: stable/2025.1
destination_branch: stable/2025.1-patches
shallow_clone: true
directory: nova
release: 2025.1
depends_on: ''
source_sha: fcab58e14f39929a6c4368872809d10cca3f2af3
