repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: virtlogd-preflight
shallow_clone: false
directory: kolla-ansible
release: master-virtlogd-preflight
depends_on: ''
source_sha: 1d479409c3e2db3bae868ef06e4055135722fab8
skip_rebase: true
skip_claude: true
previous_source_sha: e6c4dc028f14a7994dcba366873573a599c2ad6c
