repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.2
destination_branch: libvirtd-tuning
shallow_clone: false
directory: kolla-ansible
release: 2025.2-libvirtd-tuning
depends_on: ''
source_sha: ce64986978bb9930ce5f5d43bc91c0f771917518
previous_source_sha: 6baf0ddeba86343b70b78d74b8b25743eca7ff6d
skip_rebase: true
skip_claude: true
