repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.1
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2025.1-periodic-stable-tox
depends_on: ''
source_sha: d48fcdb61282f3fee76463c273805809c3ab9649
previous_source_sha: e8c4ae54c57188cbb615f199352838a2f5d8ce36
skip_rebase: true
skip_claude: true
