repo: https://opendev.org/openstack/kolla-ansible
source_branch: stable/2025.1
destination_branch: periodic-stable-tox
shallow_clone: false
directory: kolla-ansible
release: 2025.1-periodic-stable-tox
depends_on: ''
source_sha: a7fc0cd67921c871c732ac24b3282d8b8ea32235
previous_source_sha: d48fcdb61282f3fee76463c273805809c3ab9649
skip_rebase: true
skip_claude: true
