repo: https://opendev.org/openstack/kolla
source_branch: stable/2025.2
destination_branch: bug/2138186
shallow_clone: false
directory: kolla
release: 2025.2
depends_on: ''
skip_rebase: true
skip_claude: true
source_sha: 91e37843fefaf46f6358093c28c966c46e6f8d2f
previous_source_sha: 25fb3945aea4000911760c22389c169a7cf8fc26
