repo: https://opendev.org/openstack/requirements
source_branch: master
destination_branch: master-patches
shallow_clone: true
directory: requirements
release: master
depends_on: ''
source_sha: 1c86c2ef671a5100dd6d47c83f5362fc5e29285d
previous_source_sha: 909226bc79180af4d676156addfc7a12bea21279
