repo: https://opendev.org/openstack/requirements
source_branch: master
destination_branch: master-patches
shallow_clone: true
directory: requirements
release: master
depends_on: ''
source_sha: 6daef3f313a96909d1b19de1c4088689be6c5564
previous_source_sha: 2897d874a900d28bbeb8ed59a78193477c76296c
