repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: kolla-virtlogd
shallow_clone: false
directory: kolla-ansible
release: master-virtlogd
depends_on: ''
source_sha: 35e77dad108ecc050a719d3494b98a02341be8e2
previous_source_sha: 428951a945ce5faf18bff829e74c29688f8a53e3
skip_rebase: true
skip_claude: true
