repo: https://opendev.org/openstack/kolla-ansible
source_branch: master
destination_branch: kolla-virtlogd
shallow_clone: false
directory: kolla-ansible
release: master-virtlogd
depends_on: ''
source_sha: b226dff34b8ab69eaee79418751ab51248d167d1
previous_source_sha: 807bfec9634b64a5da29d0265bed2bb17f4050e0
skip_rebase: true
skip_claude: true
