#!/bin/bash -e

# $1: is an OpenStack release version -- for example 2024.1

cd ~/kerbside-patches
. buildconfig.sh

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Building patched source tree${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

# Fetch kerbside
echo -e "${H2}Cloning kerbside${Color_Off}"
mkdir src
cd src
git clone https://github.com/shakenfist/kerbside
tar cvf kerbside.tgz kerbside
cd ..
echo

# Apply patches. We skip tests here because there are separate CI jobs to
# cover that and the tests take ages to run.
declare -a directories
projects=$(find . -type f -name "config.yaml" | cut -f 2 -d "/")
for project in ${projects}; do
    release=$(yq -r .release ${project}/config.yaml)
    if [ "${release}" == "${1}" ]; then
        directories+=(${directory})
    fi
done

for directory in "${directories[@]}"; do
    echo -e "${H2}Applying patches from ${directory}${Color_Off}"
    ./testapply.sh --skip-tests ${directory}
done

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Patched source tree finalized.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"