#!/bin/bash -e

# $1: is an OpenStack release version -- for example 2024.1
target_release="${1}"

. /etc/os-release
echo "Claimed OS name: ${NAME}"
if [ "${NAME}" == "Rocky Linux" ]; then
    TOPDIR="/home/cloud-user/kerbside-patches"
else
    TOPDIR="/home/${ID}/kerbside-patches"
fi

. "${TOPDIR}/buildconfig.sh"

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Bootstrap Kolla-Ansible into a venv${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Make venv${Color_Off}"
python3 -mvenv /srv/kolla-ansible/venv
. /srv/kolla-ansible/venv/bin/activate

echo -e "${H2}Log python binary locations${Color_Off}"
echo "pip3 ${Arrow} "$(which pip3)
echo "python3 ${Arrow} "$(which python3)
echo

echo -e "${H2}Install Ansible${Color_Off}"
ansible_core=""
if [ "${target_release}" == "2024.1" ]; then
    ansible_core="ansible-core<2.17"
elif [ "${target_release}" == "2024.2" ]; then
    ansible_core="ansible-core>=2.16,<2.18"
else
    ansible_core="ansible-core>=2.16,<2.18"
fi
pip3 install -U ${ansible_core} ansible "selinux<0.3.0" dbus-python
echo

# if [ "${NAME}" == "Rocky Linux" ]; then
#     echo -e "${H2}Install selinux in system python for Rocky linux${Color_Off}"
#     /usr/bin/pip3 install "selinux<0.3.0"
#     echo
# fi

echo -e "${H2}Install docker python libraries${Color_Off}"
pip3 install docker
echo

echo -e "${H2}Install patched Kolla-Ansible${Color_Off}"
cd "${TOPDIR}/src/kolla-ansible"
pip3 install -e .
echo

echo -e "${H2}Install Kolla-Ansible dependencies${Color_Off}"
export PATH=$PATH:/usr/local/bin
kolla-ansible install-deps
echo

echo -e "${H2}Bootstrap inventory${Color_Off}"
mkdir /etc/kolla
cp -r etc/kolla /etc/
cp ansible/inventory/all-in-one /etc/kolla
echo

echo -e "${H2}Copy globals.yml${Color_Off}"
cd ../..
cp etc/globals-${target_release}.yml /etc/kolla/globals.yml
echo

echo -e "${H2}Tweak /etc/hosts${Color_Off}"
sed -i '1s/^/10.0.2.2 kolla\n\n/' /etc/hosts
echo

if [ -e /etc/cloud/templates/hosts.redhat.tmpl ]; then
    echo -e "${H2}Tweak /etc/hosts template for cloud-init${Color_Off}"
    sed -i '1s/^/10.0.2.2 kolla\n\n/' /etc/cloud/templates/hosts.redhat.tmpl
echo
fi

echo -e "${H2}Generate passwords${Color_Off}"
kolla-genpwd
echo

echo -e "${H2}Make certificates${Color_Off}"
kolla-ansible certificates -i /etc/kolla/all-in-one
echo

echo -e "${H2}Bootstrap servers${Color_Off}"
kolla-ansible bootstrap-servers -i /etc/kolla/all-in-one
echo

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Kolla-Ansible bootstrapped.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"