#!/bin/bash -e

# $1: is an OpenStack release version -- for example 2024.1
# $2: is the target topology (all-in-one or multinode)
target_release="${1}"
topology="${2}"

. ./_build/common.sh
. /etc/os-release

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Bootstrap Kolla-Ansible into a venv${Color_Off}"
echo
echo -e "${H1}python3: "$(which python3)"${Color_Off}"
echo -e "${H1}pip3: "$(which pip3)"${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Make venv for '${ID}' distro${Color_Off}"
if [ "${ID}" == "rocky" ]; then
    dnf install python3-libselinux libselinux-python3
fi

python3 -mvenv --system-site-packages /srv/kolla-ansible/venv
. /srv/kolla-ansible/venv/bin/activate

echo -e "${H2}Log python binary locations${Color_Off}"
echo "pip3 ${Arrow} "$(which pip3)
echo "python3 ${Arrow} "$(which python3)
echo

echo -e "${H2}Log python version${Color_Off}"
python3 --version
echo

echo -e "${H2}Install dependencies${Color_Off}"
ansible_core=""
if [ "${target_release}" == "2024.1" ]; then
    ansible_core="ansible-core<2.17"
elif [ "${target_release}" == "2024.2" ]; then
    ansible_core="ansible-core>=2.15,<2.18"
else
    ansible_core="ansible-core>=2.17,<2.19"
fi
pip3 install -U ${ansible_core} ansible dbus-python selinux
echo

echo -e "${H2}Upgrade the POSIX ansible collection${Color_Off}"
ansible-galaxy collection install ansible.posix --upgrade
echo

echo -e "${H2}Install docker python libraries${Color_Off}"
pip3 install docker
echo

echo -e "${H2}Install patched Kolla-Ansible${Color_Off}"
cd "${topsrcdir}/kolla-ansible"
pip3 install -e .
echo

echo -e "${H2}Install Kolla-Ansible dependencies${Color_Off}"
export PATH=$PATH:/usr/local/bin
kolla-ansible install-deps
echo

echo -e "${H2}Bootstrap inventory${Color_Off}"
mkdir -p /etc/kolla
cp -r etc/kolla /etc/
cd "${topdir}"
cat etc/inventory-${topology}-${target_release} | \
        sed "s|USER|${SUDO_USER}|g" \
        > /etc/kolla/inventory
echo

echo -e "${H2}Copy globals.yml${Color_Off}"
cp etc/globals-${target_release}.yml /etc/kolla/globals.yml
echo

if [ "${topology}" == "all-in-one" ]; then
echo -e "${H2}Tweak /etc/hosts${Color_Off}"
    sed -i "1s/^/10.0.2.2 kolla\n\n/" /etc/hosts
    echo

    if [ -e /etc/cloud/templates/hosts.redhat.tmpl ]; then
        echo -e "${H2}Tweak /etc/hosts template for cloud-init${Color_Off}"
        sed -i "1s/^/10.0.2.2 kolla\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        echo
    fi
else
    sed -i "1s/^/10.0.2.2 deploy\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.10 control-1\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.11 control-2\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.20 compute-1\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.21 compute-2\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.30 kerbside-1\n\n/" /etc/hosts
    sed -i "1s/^/10.0.2.31 kerbside-2\n\n/" /etc/hosts
    echo

    if [ -e /etc/cloud/templates/hosts.redhat.tmpl ]; then
        echo -e "${H2}Tweak /etc/hosts template for cloud-init${Color_Off}"
        sed -i "1s/^/10.0.2.2 deploy\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.10 control-1\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.11 control-2\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.20 compute-1\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.21 compute-2\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.30 kerbside-1\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        sed -i "1s/^/10.0.2.31 kerbside-2\n\n/" /etc/cloud/templates/hosts.redhat.tmpl
        echo
    fi
fi

echo -e "${H2}Dump /etc/hosts${Color_Off}"
cat /etc/hosts
echo

echo -e "${H2}Generate passwords${Color_Off}"
kolla-genpwd
echo

echo -e "${H2}Make certificates${Color_Off}"
kolla-ansible certificates -i /etc/kolla/inventory
echo

echo -e "${H2}Bootstrap servers${Color_Off}"
kolla-ansible bootstrap-servers -i /etc/kolla/inventory
echo

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Kolla-Ansible bootstrapped.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"
