#!/bin/bash -e

cd /srv/shakenfist/kerbside-patches
. buildconfig.sh
topdir=$(pwd)

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Building container images${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Build configuration${Color_Off}"
echo -e "${H1}    Targets: ${build_targets}${Color_Off}"
echo -e "${H1}    Images: ${build_images}${Color_Off}"
echo -e "${H1}    CI SHA: ${CI_COMMIT_SHORT_SHA}${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Building images${Color_Off}"
mkdir -p ${topdir}/archive/
./imagebuild.sh --build-targets "${build_targets}" --build-images "${build_images}"

echo
echo -e "${H2}Built images${Color_Off}"
docker image list

echo
echo -e "${H2}Pushing to the CI registry${Color_Off}"

debian_codename="bookworm"
for target in ${build_targets}; do
    for image in $(docker image list --format json | \
        jq --slurp -r ".[] | select(.Tag == \"${target}-${CI_COMMIT_SHORT_SHA}\") | .Repository"); do
        echo -e "    ${image}:${target}-${CI_COMMIT_SHORT_SHA} ${Arrow} 192.168.1.5:4000/openstack.${image}:${target}-debian-${debian_codename}"
        docker image tag ${image}:${target}-${CI_COMMIT_SHORT_SHA} \
            192.168.1.5:4000/openstack${image}:${target}-debian-${debian_codename}
        docker image push \
            192.168.1.5:4000/openstack${image}:${target}-debian-${debian_codename}

        echo -e "    ${image}:${target}-${CI_COMMIT_SHORT_SHA} ${Arrow} 192.168.1.5:4000/openstack.${image}:${target}-debian-${debian_codename}"
        docker image tag ${image}:${target}-${CI_COMMIT_SHORT_SHA} \
            192.168.1.5:4000/openstack${image}:${target}-${CI_COMMIT_SHORT_SHA}-debian-${debian_codename}
        docker image push \
            192.168.1.5:4000/openstack${image}:${target}-${CI_COMMIT_SHORT_SHA}-debian-${debian_codename}
    done
done

echo
trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Container image build complete.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"