#!/usr/bin/python
import sys


# The format of these patch files is:
#
# ...header (commit, author, date,etc)
# (blank line)
#     commit
#     commit
#     commit
# (blank line)
# diff --git ...
with open(sys.argv[1], 'r') as f:
    # Skip over header
    while line := f.readline():
        if len(line.rstrip()) == 0:
            break

    commit = []
    while line := f.readline():
        if line.startswith('diff --git '):
            break
        commit.append(line.rstrip())

# We now have the commit message. Remove the first four spaces from each line.
cleaned_commit = []
for line in commit:
    if line.startswith('    '):
        cleaned_commit.append(line[4:])
    else:
        cleaned_commit.append(line)

# Remove final blank line if it exists
if len(cleaned_commit[-1].rstrip()) == 0:
    cleaned_commit = cleaned_commit[:-1]

outfile = f'{sys.argv[1]}-message'
print(f'Creating {outfile}')
with open(outfile, 'w') as f:
    f.write('\n'.join(cleaned_commit))
