#!/bin/bash -e

cd /home/cloud-user/kerbside-patches
. buildconfig.sh

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Install Kolla-Ansible${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Run pre-checks${Color_Off}"
kolla-ansible -i /etc/kolla/all-in-one prechecks

echo -e "${H2}Deploy servers${Color_Off}"
kolla-ansible -i /etc/kolla/all-in-one deploy

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Kolla-Ansible installed.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"