#!/bin/bash -e

. ./_build/common.sh
. /srv/kolla-ansible/venv/bin/activate

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Install OpenStack clients${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

cd "${topsrcdir}"

for client in openstacksdk python-openstackclient; do
    if [ -e ${client} ]; then
        cd ${client}

        echo -e "${H2}Installing ${client}${Color_Off}"
        pip3 install -e .
        echo

        cd ..
    else
        pip3 install ${client}
    fi

    for executable in $(pip3 show -f ${client} | grep "/bin/" | sed 's/.*\///'); do
        ln -s /srv/kolla-ansible/venv/bin/${executable} /usr/local/bin/
        echo "Linked /srv/kolla-ansible/venv/bin/${executable} ${Arrow} /usr/local/bin/"
    done
    echo
done

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Clients installed.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"