#!/bin/bash -e

. ./_build/common.sh
. /srv/kolla-ansible/venv/bin/activate
. tools/set-ca-path

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Post installation Kolla-Ansible steps${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Post deply${Color_Off}"
kolla-ansible post-deploy -i /etc/kolla/inventory
echo

. /etc/kolla/admin-openrc.sh

echo -e "${H2}Dump cloud connection details${Color_Off}"
printenv | grep OS_
echo

echo -e "${H2}Check OS_CACERT exists${Color_Off}"
if [ ! -e ${OS_CACERT} ]; then
    echo "CA cert not at ${OS_CACERT}!"
    exit 1
fi
echo

echo -e "${H2}Run Kolla-Ansible init-runonce${Color_Off}"
export ENABLE_EXT_NET=1
export EXT_NET_CIDR='10.0.2.0/24'
export EXT_NET_RANGE='start=10.0.2.100,end=10.0.2.150'
export EXT_NET_GATEWAY='10.0.2.1'

cd src/kolla-ansible/tools
. ./init-runonce
echo

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Kolla-Ansible post install steps complete.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"