#!/bin/bash -e

cd /home/cloud-user/kerbside-patches
. buildconfig.sh

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Post installation Kolla-Ansible steps${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo -e "${H2}Post deply${Color_Off}"
kolla-ansible -i /etc/kolla/all-in-one post-deploy
echo

. /etc/kolla/admin-openrc.sh

export ENABLE_EXT_NET=1
export EXT_NET_CIDR='10.0.2.0/24'
export EXT_NET_RANGE='start=10.0.2.100,end=10.0.2.150'
export EXT_NET_GATEWAY='10.0.2.1'

cd src/kolla-ansible/tools
. ./init-runonce
echo

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Kolla-Ansible post install steps complete.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"