#!/bin/bash -e

. ./_build/common.sh
. /srv/kolla-ansible/venv/bin/activate

# We must set the CA path _after_ we load the admin openrc
. /etc/kolla/admin-openrc.sh
. tools/set-ca-path

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Download test image and setup glance${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

if [ ! -e /srv/shakenfist/uefi-latency-guest.qcow2 ]; then\
    echo
    echo "Downloading test image..."
    wget -q https://images.shakenfist.com/testimages/uefi-latency-guest.qcow2 \
        -O /srv/shakenfist/uefi-latency-guest.qcow2

    echo "Pushing test image to glance..."
    /usr/local/bin/openstack image create --public --disk-format qcow2 \
        --container-format bare \
        --file /srv/shakenfist/uefi-latency-guest.qcow2 uefi-latency-guest
fi

echo
imageid=$(/usr/local/bin/openstack image list -f json | \
    jq -e -r ".[] | select(.Name == \"uefi-latency-guest\") | .ID")
echo "... image id is ${imageid}"

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Setup image${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

/usr/local/bin/openstack image set --property hw_video_ram=64 ${imageid}
/usr/local/bin/openstack image set --property hw_firmware_type=uefi ${imageid}
/usr/local/bin/openstack image set --property hw_sound_model=usb ${imageid}
/usr/local/bin/openstack image set --property hw_usb_model=qemu-xhci ${imageid}

/usr/local/bin/openstack image show ${imageid}

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Setup flavor${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

/usr/local/bin/openstack flavor create vdi --ram 4096 --disk 200 --vcpus 4 \
    --property hw_video:ram_max_mb=64

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Start test instance${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

instancename="test-$$"
/usr/local/bin/openstack server create --flavor vdi --image ${imageid} \
    --network public1 ${instancename}

start=$(date +"%s")
now=$(date +"%s")
while [ $(( ${now} - ${start} )) -lt 300 ]; do
    status=$(/usr/local/bin/openstack server show ${instancename} -f json | jq -e -r ".status")
    if [ ${status} == 'ACTIVE' ]; then
        break
    fi
    if [ ${status} == 'ERROR' ]; then
        echo "... instance is in error status"
        echo
        /usr/local/bin/openstack server show ${instancename}
        exit 1
    fi
    echo "... instance status is ${status}"

    sleep 10
    now=$(date +"%s")
done

echo
echo "... instance status is ${status}"

if [ ${status} != 'ACTIVE' ]; then
    echo "... instance never became active"
    exit 1
fi

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}List libvirt domains${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

docker exec nova_libvirt virsh list

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Dump libvirt domain XML for instance${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

docker exec nova_libvirt virsh dumpxml 1

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Make assertions about the domain XML${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

docker exec nova_libvirt virsh dumpxml 1 > /tmp/domain.xml
if [ $(grep -c "graphics type='spice'" /tmp/domain.xml || true) -lt 1 ]; then
    echo "...graphics type='spice' missing from domain XML"
    exit 1
fi
if [ $(grep -c "sound model" /tmp/domain.xml || true) -lt 1 ]; then
    echo "...sound model missing from domain XML"
    exit 1
fi
if [ $(grep -c "controller type='usb'" /tmp/domain.xml || true) -lt 1 ]; then
    echo "...controller type='usb' missing from domain XML"
    exit 1
fi

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Create console${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

consoleurl=$(/usr/local/bin/openstack console url show ${instancename} --spice-direct -f json | \
    jq -e -r ".url")
consoletoken=$(echo ${consoleurl} | sed 's/.*token=//')

echo
echo "... console url is ${consoleurl}"
echo "... console token is ${consoletoken}"

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Lookup console connection details${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

connjson=$(/usr/local/bin/openstack console connection show ${consoletoken} -f json)
connhost=$(echo ${connjson} | jq -e -r ".host")
connport=$(echo ${connjson} | jq -e -r ".port")

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Attempt a direct connection to the hypervisor${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

echo
echo "... connection is ${connhost}:${connport}, attempting..."
timeout 5 python3 ${topdir}/tools/spice-connect.py ${connhost} ${connport}

echo
echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}Attempt to fetch a .vv file from Kerbside${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"

curl ${consoleurl}

trap - EXIT

echo -e "${H1}==================================================${Color_Off}"
echo -e "${H1}OpenStack console test complete.${Color_Off}"
echo -e "${H1}==================================================${Color_Off}"
