#!/bin/bash

# We need at least python 3.12 for modern versions of Kolla Ansible
# (those post 2024.2).

. /etc/os-release
echo "Claimed OS name: ${NAME}"
if [ "${NAME}" == "Rocky Linux" -a "${VERSION_ID}" == "9.0" ]; then
    dnf update
    dnf upgrade
    dnf install -y python3.12 python3.12-pip python3.12-wheel python3.12-devel \
        dbus-daemon libselinux-devel
    rm -f /usr/bin/python /usr/bin/python3 /usr/bin/pip3
    ln -s /usr/bin/python3.12 /usr/bin/python
    ln -s /usr/bin/python3.12 /usr/bin/python3
    ln -s /usr/bin/pip3.12 /usr/bin/pip3
    echo "Upgraded OS python to 3.12."
    /usr/bin/pip3.12 install "selinux<0.3.0"
else
    echo "OS is not Rocky Linux below v10, skipping."
fi

echo