#!/bin/bash

. /etc/os-release
echo "Claimed OS name: ${NAME}"
if [ "${NAME}" == "Rocky Linux" ]; then
  dnf update
  dnf install -y python3.12 python3.12-pip python3.12-wheel python3.12-devel
  rm -f /usr/bin/python /usr/bin/python3 /usr/bin/pip3
  ln -s /usr/bin/python3.12 /usr/bin/python
  ln -s /usr/bin/python3.12 /usr/bin/python3
  ln -s /usr/bin/pip3.12 /usr/bin/pip3
  echo "Upgraded OS python to 3.12."
else
  echo "OS is not Rocky Linux, skipping."
fi
