repo: https://opendev.org/openstack/kolla
source_branch: master
destination_branch: kolla-virtlogd
shallow_clone: false
directory: kolla
release: master-virtlogd
depends_on: ''
skip_rebase: true
skip_claude: true
source_sha: 108660d64406067b5d066c612f5de882d45b0e24
previous_source_sha: 8108d3b8c8c1e714f7d9e62311344346ca9f3a4c
