name: Build images for test installs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build_images:
    name: "Build images for ${{ matrix.test.release }} on ${{ matrix.test.container_distro }}"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
            'name': 'build-debian-2025.1',
            'release': '2025.1',
            'base': 'debian:12',
            'baseuser': 'debian',
            'container_distro': 'debian',
            'container_distro_version': 'bookworm'
          },
          {
            'name': 'build-debian-master',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'all-in-one',
            'container_distro': 'debian',
            'container_distro_version': 'bookworm'
          },
          {
            'name': 'build-ubuntu-master',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'all-in-one',
            'container_distro': 'ubuntu',
            'container_distro_version': 'noble'
          },
        ]
    runs-on: [self-hosted, vm, 'debian-12', 'xl']
    timeout-minutes: 180
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Checkout kerbside-patches
        uses: actions/checkout@v4
        with:
          path: kerbside-patches
          fetch-depth: 0

      - name: Install dependencies on local runner
        run: |
          . $GITHUB_ENV
          cd kerbside-patches

          ./_build/install-build-dependencies.sh
          ./_build/setup-local-build-environment.sh
          ./_build/add-insecure-ci-registry.sh

          # This is terrible, but its easier than reloading groups
          sudo chmod ugo+rw /var/run/docker.sock

      - name: Ensure CI OCI registry works
        env:
          CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
        run: |
          . $GITHUB_ENV

          identifier=$(hostname | sed 's/\..*//')

          echo ${CI_REGISTRY_TOKEN} | docker login \
              192.168.1.12:4000 --username kolla-imgs --password-stdin

          docker image pull quay.io/lib/python:latest
          docker image tag quay.io/lib/python:latest 192.168.1.12:4000/openstack/kolla-images/ci_heartbeat:${identifier}
          docker image push 192.168.1.12:4000/openstack/kolla-images/ci_heartbeat:${identifier}

      - name: Build patched repositories
        run: |
          . $GITHUB_ENV
          cd kerbside-patches
          ./_build/assemble-source.sh --use-ci-patches ${{ matrix.test.release }}

      - name: Build container images
        id: build_images
        env:
          CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
        run: |
          . $GITHUB_ENV
          cd kerbside-patches

          hash=$(./_build/calculate-container-hash.sh \
              kolla kolla-2* \
              nova nova-2* \
              requirements requirements-2* \
              etc src _build tools )

          image_tag="${hash}-${{ matrix.test.container_distro_version }}"
          ./_build/build-containers.sh \
              --use-ci-registry \
              --registry-username kolla-imgs \
              --registry-token "${CI_REGISTRY_TOKEN}" \
              --build-targets "${{ matrix.test.release }}" \
              --build-images all \
              --image-tag ${image_tag} \
              --dont-fetch-images

          echo "image_tag=${{ matrix.test.release }}-${image_tag}" >> ${GITHUB_OUTPUT}

      # We have the output of the build job and its config, regardless of success or failure
      - name: Archive build config and logs
        if: always()
        run: |
          . $GITHUB_ENV

          archive_path="/tmp/build-${{ matrix.test.release}}-${{ matrix.test.container_distro }}"
          mkdir ${archive_path}
          cp kerbside-patches/archive/build.log ${archive_path}/
          cp kerbside-patches/archive/kolla-build.conf ${archive_path}/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-${{ matrix.test.release }}-${{ matrix.test.container_distro }}
          retention-days: 14
          if-no-files-found: error
          path: /tmp/build-${{ matrix.test.release}}-${{ matrix.test.container_distro }}

      - name: Archive patched source
        if: success()
        run: |
          . $GITHUB_ENV
          cd kerbside-patches

          mkdir /tmp/bundle
          mv src/*.tgz /tmp/bundle/
          cd /tmp
          zip -r bundle.zip bundle

      - uses: actions/upload-artifact@v4
        id: upload_source
        if: success()
        with:
          name: source-${{ matrix.test.release }}-${{ matrix.test.container_distro }}
          retention-days: 90
          if-no-files-found: error
          path: /tmp/bundle.zip

      # This works around the limited support in Github Actions for outputs from matrices
      - name: Write outputs to a temporary file
        if: success()
        run: |
          echo "{" \
              "\"release\": \"${{ matrix.test.release }}\"," \
              "\"image_tag\": \"${{ steps.build_images.outputs.image_tag }}\"," \
              "\"source_artifact\": \"${{ steps.upload_source.outputs.artifact-url }}\"" \
              "}" >> /tmp/result.json

      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: result-${{ matrix.test.release }}-${{ matrix.test.container_distro }}
          retention-days: 14
          if-no-files-found: error
          path: /tmp/result.json

  aggregate_results:
    name: "Aggregate results"
    needs: build_images
    runs-on: ubuntu-latest
    outputs:
      all_results: ${{ steps.combine.outputs.results }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Combine results and expose as an output
        id: combine
        run: |
          # Collect all results into a JSON array
          results="["
          for dir in result-*/; do
            value=$(cat "${dir}result.json")
            results="${results}${value},"
          done

          # Terminate array and remove trailing comma
          results="${results%,}]"
          echo "results=${results}" >> $GITHUB_OUTPUT
          
  test_installs:
    name: "Build a test cloud for ${{ matrix.test.description }} using ${{ matrix.test.container_distro }}"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
            'name': '2025.1-debian12-aio',
            'description': 'OpenStack 2025.1 on Debian 12 all-in-one',
            'release': '2025.1',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'all-in-one',
            'runs_on': 'debian-12',
            'container_distro': 'debian'
          },
          {
            'name': 'master-debian12-aio',
            'description': 'OpenStack master on Debian 12 all-in-one',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'all-in-one',
            'runs_on': 'debian-12',
            'container_distro': 'debian'
          },
          {
            'name': 'master-rocky10-aio',
            'description': 'OpenStack master on Rocky 10 all-in-one',
            'release': 'master',
            'base': 'rocky:10',
            'baseuser': 'cloud-user',
            'topology': 'all-in-one',
            'runs_on': 'debian-12',
            'container_distro': 'debian'
          },
          {
            'name': 'master-debian12-multi',
            'description': 'OpenStack master on Debian 12 multinode',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'multinode',
            'runs_on': 'debian-12',
            'container_distro': 'debian'
          },
        ]
    runs-on: [self-hosted, vm, '${{ matrix.test.runs_on }}']
    needs: [build_images, aggregate_results]
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Log incoming results
        id: incoming
        run: |
          echo "State of workspace:"
          ls -lrt

          echo
          echo "Results from image build step:"
          echo '${{ needs.aggregate_results.outputs.all_results }}' | python3 -m json.tool

          echo "Export results specific to this job..."
          image_tag=$(cat result-${{ matrix.test.release }}-${{ matrix.test.container_distro }}/result.json | jq -r .image_tag)
          echo "image_tag=${image_tag}" >> $GITHUB_OUTPUT

      - name: Setup test environment
        uses: shakenfist/actions/setup-kerbside-environment@main
        with:
          base: ${{ matrix.test.base }}
          base_user: ${{ matrix.test.baseuser }}
          openstack_release: ${{ matrix.test.release }}
          topology: ${{ matrix.test.topology }}

      - name: Dump CI environment details
        run: |
          cat ci-environment.sh

      - name: Log getent resolution for kolla
        if: "contains(matrix.test.topology, 'all-in-one')"
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo getent ahostsv4 kolla'

      - name: Extract source from image build step
        run: |
          . $GITHUB_ENV

          echo "Extracting source from build step..."
          cd ${GITHUB_WORKSPACE}/source-${{ matrix.test.release }}-${{ matrix.test.container_distro }}
          unzip bundle.zip
          cd bundle
          ls -lrt

          echo
          echo "Using that source to bootstrap kerbside-patches src directory..."
          cd ${GITHUB_WORKSPACE}/kerbside-patches
          mkdir -p src
          for item in ${GITHUB_WORKSPACE}/source-${{ matrix.test.release }}-${{ matrix.test.container_distro }}/bundle/*.tgz; do
              echo "Extracting ${item}."
              tar xzf ${item}
          done

          echo
          echo "State of source..."
          ls -lrt

      - name: Bootstrap Kolla-Ansible
        env:
          CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
        run: |
          . $GITHUB_ENV

          script="cd /srv/shakenfist/kerbside-patches;"
          script="${script} sudo ./tools/bootstrap-kolla-ansible"
              script="${script} --registry-token  ${CI_REGISTRY_TOKEN}"
              script="${script} --image-tag  ${{ steps.incoming.image_tag }}"
              script="${script} --build-targets ${{ matrix.test.release }}"
              script="${script} --topology ${{ matrix.test.topology }};"
          
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 "${script}"

      - name: Log into the docker registry on every node
        env:
          CI_REGISTRY_TOKEN: ${{ secrets.CI_REGISTRY_TOKEN }}
        run: |
          . $GITHUB_ENV
          . ci-environment.sh

          for node in ${nodes}; do
              node_address=${!node}
              echo "${node} is at ${node_address}"
              echo
              ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  ${{ matrix.test.baseuser }}@${node_address} \
                  "echo ${CI_REGISTRY_TOKEN} | docker login 192.168.1.12:4000 --username kolla-imgs --password-stdin"
              echo
          done

      - name: Pull images
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/ka pull -i /etc/kolla/inventory'

      - name: Run pre-checks
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/ka prechecks -i /etc/kolla/inventory'

      - name: Deploy
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/ka deploy -i /etc/kolla/inventory'

      - name: Install patched OpenStack clients
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/install-openstack-clients'

      - name: Dump internal VIP CA cert details
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'openssl s_client -showcerts -connect 10.0.2.3:5000'

      - name: Dump CA cert bundle
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo openssl storeutl -noout -text -certs /etc/kolla/certificates/ca/root.crt'

      - name: Post install Kolla-Ansible setup
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/postinstall-kolla-ansible --use-ci-registry'

      - name: Verify that the haproxy is configured correctly for the Kerbside API
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'curl -v -k https://10.0.2.3:13002'

      - name: Dump Kerbside API CA cert details
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'openssl s_client -showcerts -connect 10.0.2.3:13002'

      - name: Attempt to start an instance with a console and connect to it
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/test-console'

      - name: Dump netstat
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo netstat -plnt || true'

      - name: Dump haproxy docker logs
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker logs haproxy || true'

      - name: Dump kerbside API docker logs
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker logs kerbside_api || true'

      - name: Dump kerbside proxy docker logs
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker logs kerbside_proxy || true'

      - name: Inspect kerbside API docker container
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker inspect kerbside_api || true'

      - name: Inspect kerbside proxy docker container
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker inspect kerbside_proxy || true'

      - name: Collect logs
        if: always()
        run: |
          . $GITHUB_ENV
          . ci-environment.sh

          mkdir -p /tmp/bundle/consoledata

          for instance_name in $(sf-client --simple instance list | cut -f 2 -d "," | grep -v name); do
              sf-client instance consoledata ${instance_name} 100000000 > /tmp/bundle/consoledata/${instance_name}
          done

          for node in ${nodes}; do
              echo
              echo
              node_address=${!node}
              echo "${node} is at ${node_address}"
              echo

              if [ "${node_address}" != "10.0.2.2" ]; then
                  script="sudo mkdir -p /srv/shakenfist/kerbside-patches"
                  script="${script}; sudo chown -R ${{ matrix.test.baseuser }}:${{ matrix.test.baseuser }} /srv/shakenfist"

                  ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                          -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${node_address} \
                          "${script}"

                  scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                      -o UserKnownHostsFile=/dev/null \
                      ${GITHUB_WORKSPACE}/kerbside-patches/tools \
                      ${{ matrix.test.baseuser }}@${node_address}:/srv/shakenfist/kerbside-patches
              fi

              ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  ${{ matrix.test.baseuser }}@${node_address} \
                  'cd /srv/shakenfist/kerbside-patches/tools; sudo ./gather-logs'
              scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  ${{ matrix.test.baseuser }}@${node_address}:/tmp/bundle.zip /tmp/bundle/${node}.zip

              mkdir -p /tmp/bundle/${node}
              cd /tmp/bundle/${node}
              unzip ../${node}.zip || true
              rm ../${node}.zip
          done

          echo
          echo
          echo "Building single bundle"
          echo
          cd /tmp/
          zip -r bundle.zip bundle


      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-${{ matrix.test.name }}
          retention-days: 90
          if-no-files-found: error
          path: /tmp/bundle.zip
