name: Ensure the cloud is still installable

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop

jobs:
  build_images:
    name: "Build docker images"
    runs-on: [self-hosted, vm]
    timeout-minutes: 180
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Install dependencies on local runner
        run: |
          sudo apt-get update
          sudo apt-get dist-upgrade -y
          sudo apt-get install -y moreutils git

      - name: Setup test environment
        uses: shakenfist/actions/setup-kerbside-environment@main
        with:
          base: debian:12
          base_user: debian
          openstack_release: master
          topology: all-in-one

      - name: Build patched repositories
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; ./_build/assemble-source.sh master'

      - name: Build container images
        run: |
          . $GITHUB_ENV

          script="cd /srv/shakenfist/kerbside-patches;"
          script="${script} hash=\$(./_build/calculate-container-hash.sh kolla kolla-2*);"
          script="${script} ./_build/build-containers.sh --use-ci-registry --build-targets master --build-images all --image-tag "\$hash-debian-bookworm" --dont-fetch-images;"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              debian@10.0.2.2 "${script}"


  functional_matrix:
    name: "Build a test cloud for ${{ matrix.test.description }}"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
            'name': 'master-debian12-aio',
            'description': 'OpenStack master on Debian 12 all-in-one',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'all-in-one'
          },
          {
            'name': 'master-rocky9-aio',
            'description': 'OpenStack master on Rocky 9 all-in-one',
            'release': 'master',
            'base': 'rocky:9',
            'baseuser': 'cloud-user',
            'topology': 'all-in-one'
          },
          {
            'name': 'master-debian12-multi',
            'description': 'OpenStack master on Debian 12 multinode',
            'release': 'master',
            'base': 'debian:12',
            'baseuser': 'debian',
            'topology': 'multinode'
          },
        ]
    runs-on: [self-hosted, vm]
    needs: build_images
    timeout-minutes: 120
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
      cancel-in-progress: true

    # NOTE(mikal): git repos are checked out to /srv/github/_work/{org}/{repo}
    # which is available as GITHUB_WORKSPACE. You can find other environment
    # variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

    steps:
      - name: Setup test environment
        uses: shakenfist/actions/setup-kerbside-environment@main
        with:
          base: ${{ matrix.test.base }}
          base_user: ${{ matrix.test.baseuser }}
          openstack_release: ${{ matrix.test.release }}
          topology: ${{ matrix.test.topology }}

      - name: Build patched repositories
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; ./_build/assemble-source.sh ${{ matrix.test.release }}'

      - name: Build container images
        run: |
          . $GITHUB_ENV

          script="cd /srv/shakenfist/kerbside-patches;"
          script="${script} hash=\$(./_build/calculate-container-hash.sh kolla kolla-2*);"
          script="${script} ./_build/build-containers.sh --use-ci-registry --build-targets master --build-images all --image-tag "\$hash-debian-bookworm" --dont-fetch-images;"

          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 "${script}"

      # - name: Disable /etc/hosts for name resolution
      #   run: |
      #     . $GITHUB_ENV
      #     ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
      #         -o UserKnownHostsFile=/dev/null \
      #         ${{ matrix.test.baseuser }}@10.0.2.2 \
      #         'sudo sed -i s"|hosts:      files dns myhostname|hosts:      dns myhostname|" /etc/nsswitch.conf'

      - name: Bootstrap Kolla-Ansible
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/bootstrap-kolla-ansible ${{ matrix.test.release }} ${{ matrix.test.topology }}'

      - name: Install Kolla-Ansible
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/install-kolla-ansible'

      - name: Install patched OpenStack clients
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/install-openstack-clients'

      - name: Dump haproxy logs
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker logs haproxy || true'

      - name: Dump kerbside proxy logs
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo docker logs kerbside_proxy || true'

      - name: Dump internal VIP CA cert details
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'openssl s_client -showcerts -connect 10.0.2.3:5000'

      - name: Dump CA cert bundle
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'sudo openssl storeutl -noout -text -certs /etc/kolla/certificates/ca/root.crt'

      - name: Post install Kolla-Ansible setup
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/postinstall-kolla-ansible'

      # - name: Dump kerbside debugging information
      #   run: |
      #     . $GITHUB_ENV
      #     ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
      #         -o UserKnownHostsFile=/dev/null \
      #         ${{ matrix.test.baseuser }}@10.0.2.2 \
      #         'cd /srv/shakenfist/kerbside-patches; sudo ./tools/inspect-kerbside'

      - name: Attempt to start an instance with a console and connect to it
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches; sudo ./tools/test-console'

      - name: Collect logs
        if: always()
        run: |
          . $GITHUB_ENV
          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2 \
              'cd /srv/shakenfist/kerbside-patches/tools; sudo ./gather-logs'
          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@10.0.2.2:/tmp/bundle.zip /tmp/bundle.zip

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-${{ matrix.test.name }}
          retention-days: 90
          if-no-files-found: error
          path: /tmp/bundle.zip