name: Ensure local container builds work

# The purpose of this workflow is that container builds still work for the
# releases I care about, with a minimum amount of my overall CI environment
# involved -- that is, it models a random user building containers on their
# local workstation.
#
# This workflow should closely follow the instructions from README.md,
# although there are some minor githubisms in here (git clones mostly).

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'data/**'
      - 'docs/**'

jobs:
  local_build_matrix:
    name: "Ensure local builds for ${{ matrix.test.release }} work"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
              'release': 'master',
              'container_distro': 'debian',
              'container_distro_version': 'trixie'
          },
        ]
    runs-on: [self-hosted, vm, 'debian-12', 'xl']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-local-${{ matrix.test.release }}
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        shell: bash
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout kerbside-patches
        uses: actions/checkout@v7
        with:
          path: kerbside-patches
          fetch-depth: 0

      # We need the actions repository to build a test instance, you wouldn't
      # need this for a normal local build, but it is imposed by this being
      # a CI job pretending to be a local build.
      - name: Checkout the actions repository
        uses: actions/checkout@v7
        with:
          repository: shakenfist/actions
          path: actions
          fetch-depth: 0

      - name: Install dependencies
        run: |
          . $GITHUB_ENV
          cd kerbside-patches
          ./_build/setup-local-build-environment.sh

          # Now that we're building on the runner, we must also do terrible
          # crimes to allow access to docker because we cannot reliably
          # reload our group membership.
          sudo chmod ugo+rw /var/run/docker.sock

      - name: Assemble source code
        run: |
          . $GITHUB_ENV
          cd kerbside-patches
          ./_build/assemble-source.sh --use-ci-patches --no-tarball ${{ matrix.test.release }}

      - name: Build containers with no local OCI registry
        run: |
          . $GITHUB_ENV
          cd kerbside-patches
          ./_build/build-containers.sh \
              --build-targets ${{ matrix.test.release }} \
              --build-images all \
              --distro ${{ matrix.test.container_distro}} \
              --distro-version ${{ matrix.test.container_distro_version }} \
              --image-tag local
