name: Rebase tests

# NOTE(mikal): git repos are checked out to /srv/github/_work/{repo}/{repo}
# which is available as GITHUB_WORKSPACE. You can find other environment
# variables at https://docs.github.com/en/actions/learn-github-actions/environment-variables

on:
  pull_request:
    branches:
      - develop
      - v*-releases
    paths-ignore:
      - 'docs/**'

jobs:
  functional_matrix:
    name: "Rebase ${{ matrix.test.description }}"
    strategy:
      fail-fast: false
      matrix:
        test: [
          {
              'description': "kolla on rocky 9",
              'name': 'rocky-9-kolla',
              'baseimage': 'sf://label/ci-images/rocky-9',
              'baseuser': 'cloud-user',
              'targets': 'kolla:master',
              'infrastructure': 'rocky-9-metal'
          },
          {
              'description': "kolla on debian 12",
              'name': 'debian-12-kolla',
              'baseimage': 'sf://label/ci-images/debian-12',
              'baseuser': 'debian',
              'targets': 'kolla:master',
              'infrastructure': 'debian-12-metal'
          },
          {
              'description': "kolla-ansible on rocky 9",
              'name': 'rocky-9-kolla-ansible',
              'baseimage': 'sf://label/ci-images/rocky-9',
              'baseuser': 'cloud-user',
              'targets': 'kolla-ansible:master',
              'infrastructure': 'rocky-9-metal'
          },
          {
              'description': "kolla-ansible on debian 12",
              'name': 'debian-12-kolla-ansible',
              'baseimage': 'sf://label/ci-images/debian-12',
              'baseuser': 'debian',
              'targets': 'kolla-ansible:master',
              'infrastructure': 'debian-12-metal'
          },
        ]
    runs-on: [self-hosted, "${{ matrix.test.infrastructure }}"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.test.name }}
      cancel-in-progress: true

    steps:
      - name: Set environment variables
        run: |
          echo "SF_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          echo "SHAKENFIST_NAMESPACE=$(hostname)" >> $GITHUB_ENV

      - name: Checkout kerbside-patches
        uses: actions/checkout@v4
        with:
          path: kerbside-patches
          fetch-depth: 0

      - name: Log targets
        run: |
          echo "Testing targets are: ${{ matrix.test.targets }}"

      - name: Install required packages
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          sudo apt-get install -y moreutils
          sudo pip3 install yq

      - name: Attempt to apply patches (2024.1)
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          cd ${GITHUB_WORKSPACE}/kerbside-patches

          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2024.1" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              ./_build/test-apply.sh --skip-tests ${project}-${branch}

              echo
              echo
            fi
          done

      - name: Attempt to apply patches (2024.2)
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          cd ${GITHUB_WORKSPACE}/kerbside-patches

          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2024.2" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              ./_build/test-apply.sh --skip-tests ${project}-${branch}

              echo
              echo
            fi
          done

      - name: Attempt to apply patches (master)
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          cd ${GITHUB_WORKSPACE}/kerbside-patches

          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "master" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              ./_build/test-apply.sh --skip-tests ${project}

              echo
              echo
            fi
          done

      - name: Build the instance which actually runs tests
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          cd ${GITHUB_WORKSPACE}/kerbside-patches/.github
          ansible-playbook -i /home/debian/ansible-hosts \
              --extra-vars "identifier=${SHAKENFIST_NAMESPACE} source_path=${GITHUB_WORKSPACE} \
              base_image=${{ matrix.test.baseimage }} base_image_user=${{ matrix.test.baseuser }}" \
              ci-topology.yml

          echo "ci-environment:"
          cat ${GITHUB_WORKSPACE}/ci-environment.sh

      - name: Copy source code to primary
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}
          rm -rf kerbside-patches/src

          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null -rp kerbside-patches \
              ${{ matrix.test.baseuser }}@${primary}:.

      - name: Install missing dependencies
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh

          if [ ${{ matrix.test.baseuser }} == "debian" ]; then
            script="set -x;"
            script="${script} sudo apt-get update;"
            script="${script} sudo apt-get dist-upgrade -y;"
            script="${script} sudo pip3 install --break-system-packages yq tox;"
            script="${script} sudo apt-get install -y moreutils libpq-dev;"
            script="${script} sudo apt-get install -y python3-dev build-essential libpcre3-dev"

            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@${primary} \
              "${script}"
          else
            script="set -x;"
            script="${script} sudo dnf update -y;"
            script="${script} sudo dnf install -y epel-release;"
            script="${script} sudo dnf config-manager --set-enabled crb;"
            script="${script} sudo pip3 install yq tox flake8;"
            script="${script} sudo dnf install -y moreutils gcc"

            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@${primary} \
              "${script}"
          fi

      - name: Deep test patches (2024.1)
        run: |
          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2024.1" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              if [ $(echo ${{ matrix.test.infrastructure }} | grep metal) ]; then
                echo
                echo -e "${Green}Running test locally${Color_Off}"
                echo
                cd ${GITHUB_WORKSPACE}/kerbside-patches
                ./_build/test-apply.sh ${project}-${branch}
              else
                echo
                echo -e "${Green}Running test on a VM${Color_Off}"
                echo
                . ${GITHUB_WORKSPACE}/ci-environment.sh
                ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${primary} \
                    "cd kerbside-patches; ./_build/test-apply.sh ${project}-${branch}"
              fi
            fi
          done

      - name: 2024.2 onwards requires a newer python than the system default in Rocky 9
        if: "!contains(matrix.test.infrastructure, 'metal')"
        run: |
          . ${GITHUB_WORKSPACE}/ci-environment.sh
          cd ${GITHUB_WORKSPACE}

          if [ ${{ matrix.test.baseuser }} == "cloud-user" ]; then
            script="set -x;"
            script="${script} cd kerbside-patches/tools;"
            script="${script} sudo ./upgrade-python;"
            script="${script} sudo pip3 install yq tox flake8"

            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ matrix.test.baseuser }}@${primary} \
              "${script}"
          fi

      - name: 2024.2 onwards requires a newer python than the system default in Rocky 9
        if: "contains(matrix.test.infrastructure, 'rocky-9-metal')"
        run: |
          cd ${GITHUB_WORKSPACE}
          rm -rf .venv
          python3.12 -mvenv .venv
          .venv/bin/pip3 install yq tox flake8

      - name: Deep test patches (2024.2)
        run: |
          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2024.2" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              if [ $(echo ${{ matrix.test.infrastructure }} | grep metal) ]; then
                echo
                echo -e "${Green}Running test locally${Color_Off}"
                echo
                cd ${GITHUB_WORKSPACE}
                if [ -e .venv ]; then
                  . .venv/bin/activate
                fi
                cd kerbside-patches
                ./_build/test-apply.sh ${project}-${branch}
              else
                echo
                echo -e "${Green}Running test on a VM${Color_Off}"
                echo
                . ${GITHUB_WORKSPACE}/ci-environment.sh
                ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${primary} \
                    "cd kerbside-patches; ./_build/test-apply.sh ${project}-${branch}"
              fi
            fi
          done

      - name: Deep test patches (2025.1)
        run: |
          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2025.1" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              if [ $(echo ${{ matrix.test.infrastructure }} | grep metal) ]; then
                echo
                echo -e "${Green}Running test locally${Color_Off}"
                echo
                cd ${GITHUB_WORKSPACE}
                if [ -e .venv ]; then
                  . .venv/bin/activate
                fi
                cd kerbside-patches
                ./_build/test-apply.sh ${project}-${branch}
              else
                echo
                echo -e "${Green}Running test on a VM${Color_Off}"
                echo
                . ${GITHUB_WORKSPACE}/ci-environment.sh
                ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${primary} \
                    "cd kerbside-patches; ./_build/test-apply.sh ${project}-${branch}"
              fi
            fi
          done

      - name: Deep test patches (2025.2)
        run: |
          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "2025.2" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              if [ $(echo ${{ matrix.test.infrastructure }} | grep metal) ]; then
                echo
                echo -e "${Green}Running test locally${Color_Off}"
                echo
                cd ${GITHUB_WORKSPACE}
                if [ -e .venv ]; then
                  . .venv/bin/activate
                fi
                cd kerbside-patches
                ./_build/test-apply.sh ${project}
              else
                echo
                echo -e "${Green}Running test on a VM${Color_Off}"
                echo
                . ${GITHUB_WORKSPACE}/ci-environment.sh
                ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${primary} \
                    "cd kerbside-patches; ./_build/test-apply.sh ${project}"
              fi
            fi
          done

      - name: Deep test patches (master)
        run: |
          Green='\033[0;32m'        # Green
          Color_Off='\033[0m'       # Text Reset

          for target in ${{ matrix.test.targets }}; do
            project=$( echo ${target} | cut -f 1 -d ":" )
            branch=$( echo ${target} | cut -f 2 -d ":" )
            echo "Considering target ${target}, ${project} branch ${branch}"

            if [[ ${branch} == "master" ]]; then
              echo
              echo -e "${Green}==================================================${Color_Off}"
              echo -e "${Green}Attempting to apply patches for ${target}${Color_Off}"
              echo -e "${Green}==================================================${Color_Off}"

              if [ $(echo ${{ matrix.test.infrastructure }} | grep metal) ]; then
                echo
                echo -e "${Green}Running test locally${Color_Off}"
                echo
                cd ${GITHUB_WORKSPACE}
                if [ -e .venv ]; then
                  . .venv/bin/activate
                fi
                cd kerbside-patches
                ./_build/test-apply.sh ${project}
              else
                echo
                echo -e "${Green}Running test on a VM${Color_Off}"
                echo
                . ${GITHUB_WORKSPACE}/ci-environment.sh
                ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null ${{ matrix.test.baseuser }}@${primary} \
                    "cd kerbside-patches; ./_build/test-apply.sh ${project}"
              fi
            fi
          done
